# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99d19a370637caad323eaf6e792e475a949f366c58808d7e61b861cd4620095b3ef83521685336b595398b391bfd7a828a90774f0d5ccb99a2ea19d27c090565

test:
  secret_key_base: 4bcfea8789a6692912acdea1556c01f88730dff9acac7ebca967f6fe759173f18b99f4a4126862fe043325b83908c13e222d867a6fac128f55f596cefb1d1682

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
